Update next.config.js
doamatto/doamatto.xyz pull request #152
Opened 2021-04-24 18:31 UTC by himanshu007-creator

#151

2021-04-24 18:34 UTC, doamatto requested changes

2021-04-24 18:34 UTC, doamatto commented on next.config.js
> +  module.exports = {
This was already declared in the first line of the document

2021-04-24 18:34 UTC, doamatto commented on next.config.js
>      config.node = {
This section would need to be altered to work with Webpack 5. Iirc it has to do with [`resolve.fallback`](https://webpack.js.org/configuration/resolve/#resolvefallback), to help point you in the right direction

2021-04-25 06:36 UTC, himanshu007-creator commented
@doamatto  , can you tell the exact code that needs to be put  please?

2021-04-25 16:39 UTC, doamatto commented
Sorry Himanshu, I'm not exactly sure what needs to be put; hence why I made the issue for me or someone else to get to later. It'll take a little bit of researching in Webpack's documentation to find out how to get it to work properly.

2021-04-30 14:34 UTC, doamatto commented
Resolved with #157.

2021-04-30 14:34 UTC, closed without merging